### ISSUE TITLE
Migrating Database And Authentication Support (AUTH0)

### ISSUE THREAD

**Issue by Sukriti-sood** [sounishnath003/450-DSA-Tracker#24]
Adding Login and Signup Options and Storing Data in Backend as On Opening website from different System will not work

**Comment by sounishnath003** [comment]
Hi @Sukriti-sood 
Greetings, 

Yes, for the last couple of days, I am also thinking to integrate the Auth because I am thinking to integrate in-app coding and compilation like Leetcode  / any other resources we have generally seen! 

Do you also want to contribute to building the platform more intuitive and better for the future!? Any sort of contribution are highly encouraged. 

Let me know?

**Comment by Sukriti-sood** [comment]
@sounishnath003 Yes I am really interested in contributing and making this better. Can you explain your idea about in-app coding and If you  have no problem so It will be more better to discuss stuff in discord server.

**Comment by sounishnath003** [comment]
### Aspects and Thoughts In My Mind
The feat. hinders around a really simple idea. In each module (ex. arrays, matrix, LL, ST, Que, etc) till now shows the listings of the questions, and after clicking on any of these you are redirected to GFG/leetcode/other sites from where the question is listed.

// * TODO
What I am thinking **without redirecting to the other sites, I will also add an in-app code-editor and the problem statement so that people can read and solve the question just from the app itself. like (Leetcode/ hackerrank / HackerEarth etc.)**

This will enhance the UX and make the Platform - **A ONE STOP SOLUTION FOR PREPARING DSA with the curated lists of Love Babbar.**

**I Hope The Idea Is Clear to you now! 📌**

**Comment by Sukriti-sood** [comment]
@sounishnath003 So, you want to add code editor and all running test and submitting problems in Same or Just  showing problem Statements.

**Comment by sounishnath003** [comment]
> @sounishnath003 So, you want to add code editor and all running test and submitting problems in Same or Just showing problem Statements.

But, first, need to migrate data to a database with authentication support!!, Let's do it first!

**Comment by Sukriti-sood** [comment]
> > @sounishnath003 So, you want to add code editor and all running test and submitting problems in Same or Just showing problem Statements.
> 
> But, first, need to migrate data to a database with authentication support!!, Let's do it first!

Ook I will Start working in 2-3 on this , Currently you are arranging problems on basis of difficulty
