### ISSUE TITLE
Upload Solution button issue

### ISSUE THREAD

**Issue by IzacVrushabh** [sounishnath003/450-DSA-Tracker#30]
Upload Solution button is not working for other topics ( like search & sort  , linkedList , matrix , etc)..
And button is also not visible for some topics ...
Please fix this issue.

**Comment by sounishnath003** [comment]
@IzacVrushabh ,

Yeah... This looks strange, 
It's been 1.5 hrs or so, I am still clueless **why this is happening!?**

sorry for the inconvenience

**Comment by sounishnath003** [comment]
Hey! @IzacVrushabh 
Hope you are doing well and engaged in the platform! Sorry for my inconvenience and delay with the FIX for navigation along with solution uploading!

*Hence It's fixed now! in the commit - [#12a5ea8](https://github.com/sounishnath003/450-DSA-Tracker/commit/12a5ea8a5e7c06f48b9671d5ba64279f96c7829b).*

Will push into the production in a while! Enjoy!

More new features coming in the way - 
1. Distrubutate access with Auth0 integrated, leading to all your devices and tracking each progress simultaneously.
2. In-App Code editor like leetcode and write the solution side by side.
3. More optimized and snappy experience.

**Comment by IzacVrushabh** [comment]
thankyou.. and when you push into the production... please notify me here.. because i want to upload my solutions asap..

**Comment by sounishnath003** [comment]
Done! Will add an editor there will help you and others!
