### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by pranitha-sridhar** [sounishnath003/450-DSA-Tracker#43]
<img width="591" alt="2021-07-23" src="https://user-images.githubusercontent.com/58912941/126746455-923f12e0-f976-41fd-8f70-0c81fb6575a5.png">

This issue is being displayed when I try to login.

**Comment by The-Anton** [comment]
Facing the same problem :( Pls, resolve it.

**Comment by Hritikror** [comment]
Pls resolve this issue as soon as possible.

**Comment by sounishnath003** [comment]
## Info: Update 
I didn’t change anything since last deployed!!. I have no context for what happened! Have to look!

> It is by netlify proxy!! I felt really sorry for this. Have to look but right this week it is hard. But till now for 2 months it is working fine! It suddenly happened.

**I am really sorry again, to all more than 1400+ active users, It is as I get it a netlify proxy issue. I have to drop a mail/something. It might take a few days. You are facing a huge mess, I know, it's unfortunate for all.**

**Comment by sounishnath003** [comment]
## Issue Has Been FIXED 😄 🎊 

@pranitha-sridhar @The-Anton  Can you please revert back to this thread?. Seems like the issue has been fixed!

![image](https://user-images.githubusercontent.com/40270033/126787620-f200ee77-5baf-4acb-b0cc-08fe723c508f.png)

**Comment by sounishnath003** [comment]
@pranitha-sridhar 

Can you please give some feedback, if it working for you also or not. Cause many people already gave feedback.!

**Comment by pranitha-sridhar** [comment]
Yes Its working now. Thank you!

**Comment by sounishnath003** [comment]
Sounds good 🍰
